### ISSUE TITLE
Android does not receive any notifications after a restart

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/MxPushNotifications#28] opened 2016-05-25 07:02 UTC
Currently we have trouble receiving notifications after an android device has restarted
 (iPhone is working fine) similar to : phonegap-build/PushPlugin#281

The notifications are working fine, after the app is opened for the first time. 
Notifications are received even after the app is closed.
However, when the android device is restarend, the notifications are not received anymore.

**Comment by KevinVlaanderen** [comment] 2016-11-08 18:00
Hi Andries. Could you tell me if this still an issue? We've changed the device registration code, a little while ago, with the intent of making the device registration code more robust. (commit f40db3914236b71d009cb06166e96693b7834f77)

**Comment by Andries-Smit** [comment] 2016-11-09 06:35
Hi Kevin,

Currently the project where this issue occurred is not under development anymore, so there has been no update recently. When I find a spare moment try again to see if this issue is still relevant.

Cheers, Andries

**Comment by twiggler** [comment] 2017-01-23 10:28
Tested against Push Notifications module  v2.2.0 via mendix mobile / pusheen.
Device: Samsung Galaxy S7

1. Send Push Notifications to device: received.
2. Rebooted device.
3. Send Push Notifications to device: received.

Cannot reproduce, closing issue

**Closed by twiggler** 2017-01-23 10:28 UTC
