### ISSUE TITLE
Sending Google messages resulting error

### ISSUE THREAD

**Issue by pimvdnoll** [mendix/MxPushNotifications#12] opened 2015-07-01 20:05 UTC
I got the error and message is not sending. Any idea?

Error parsing JSON 

Unexpected character (<) at position 0.
	at org.json.simple.parser.Yylex.yylex(Unknown Source)
	at org.json.simple.parser.JSONParser.nextToken(Unknown Source)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.json.simple.JSONValue.parseWithException(Unknown Source)
	at pushnotifications.implementation.gcm.GCMPacketListener.processPacket(GCMPacketListener.java:33)
	at org.jivesoftware.smack.XMPPConnection$ListenerWrapper.notifyListener(XMPPConnection.java:1233)
	at org.jivesoftware.smack.XMPPConnection$ListenerNotification.run(XMPPConnection.java:1143)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by simo101** [comment] 2015-07-02 07:19
I have seen this error before. But i have yet to find the cause. I believe it is to do with the response back from the GCM and it sending nothing back as a response. I tried to investigate the issue, but couldn't resolve it. The message does get sent to google and to the device, so i thought that for now i would ignore this error message. If you find a fix then please let me know and i will include the fix.

**Comment by pimvdnoll** [comment] 2015-07-02 07:29
The only thing is that there is a difference between <data:gcm en <gcm

**Comment by simo101** [comment] 2016-04-23 10:05
This is a duplicate of #16

**Closed by simo101** 2016-04-23 10:05 UTC
